### ISSUE TITLE
[Bug] Captive UI should correctly show whether network is known or not

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#112]
### Pre-submission checklist

- [X] I checked that no other Bug Report describing my problem exists.
- [X] I am running the latest stable or prerelease firmware.
- [X] My board is on the [list of maintained boards](https://wiki.openshock.org/hardware/boards/#fully-maintained).
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### Board

Pishock 2023

### Firmware version

1.0.0-rc.4

### Flashing method

See RELEASE.md

### Describe what happened as precisely as possible.

After you connect to a WiFi network, the network list does not accurately show that the network you connected to is now a known network.

Until you reboot the board, it keeps showing as unknown network.

The reverse is also true when pressing the Forget Network button.

### Describe what you expected to happen instead.

Network list should accurately show whether a network is known or not, after you change that fact

### In as much detail as possible, describe the exact steps you took to make the problem appear.

Option 1:
- Successfully connect to previously unknown wifi network
- The network list keeps showing said wifi network as **not** having any saved credentials

Option 2:
- Go to a known networks' settings
- Press "Forget"
- The network list keeps showing said wifi network as **having** saved credentials

**Comment by hhvrc** [comment]
This is fixed in #113
