### ISSUE TITLE
[Bug] RTM Pin not changed on runtime only on restart

### ISSUE THREAD

**Issue by Kyobinoyo** [OpenShock/Firmware#114]
### Pre-submission checklist

- [X] I checked that no other Bug Report describing my problem exists.
- [X] I am running the latest stable or prerelease firmware.
- [X] My board is on the [list of maintained boards](https://wiki.openshock.org/hardware/boards/#fully-maintained).
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### Board

Pishock 2023

### Firmware version

1.0.0-rc.4

### Flashing method

esptool via powershell

### Describe what happened as precisely as possible.

RTMPIN setting does not change on runtime, only saves and gets applied after restart

### Describe what you expected to happen instead.

should apply on runtime without the need of a restart

### In as much detail as possible, describe the exact steps you took to make the problem appear.

setup esp and change rtm pin setting without restart

### Other remarks

nope thanks for listening to my ted talk

**Comment by LucHeart** [comment]
This should be fixed no?
