### ISSUE TITLE
[Feature] Support board: Wemos Lolin S2 Mini

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#13]
See: https://discord.com/channels/1078124408775901204/1157221049281302538

## Development
- [x] Add to CI
- [x] Configure status LED
- [ ] Configure TX pin if applicable

## Testing
- [x] Test board boots
- [x] Test captive portal appears in network list
- [ ] Test captive portal works

**Comment by LucHeart** [comment]
Implemented already.
