### ISSUE TITLE
Built firmware binaries are broken

### ISSUE THREAD

**Issue by LucHeart** [OpenShock/Firmware#19]
Firmware bins compiled by github actions dont seem to work at all

**Comment by hhvrc** [comment]
Firmware*

**Comment by redmushie** [comment]
I think it's time to add issue templates because this issue contains zero useful information for me to even understand what you tried, let alone reproduce it ._.

**Comment by LucHeart** [comment]
Try to flash a built artifact, it doesnt work, straightup no output, nothing-

**Comment by LucHeart** [comment]
e.g. https://github.com/OpenShock/Firmware/suites/16850240278/artifacts/962381648

**Comment by redmushie** [comment]
> a build artifact

What artifact?

> try to flash

What are you flashing? How are you flashing? To what board are you flashing?

**Comment by LucHeart** [comment]
The built artifacts that can be found under the actions section on github obviously. Latest develop OpenShock_Wemos-D1-Mini-ESP32. Prettysure all are broken tho.

Am trying to flash a D1 mini, esptool, esptooljs, doesnt matter.

**Comment by redmushie** [comment]
Yes, it matters.

Artifacts are fine for me.
Output is fine for me.

If you don't specify exactly what commands you're using with their exact arguments, there's no way for me to even _try_ to reproduce what you're seeing, and I'd close the issue as non-reproducible.

**Comment by LucHeart** [comment]
There is not more information to be give ngl. here have a list to reproduce, its as I already described.

1. Download latest D1 mini firmware from artifacts section (develop)
2. Connect your ESP-32 (D1 mini) via usb
3. Go to https://espressif.github.io/esptool-js/
4. Connect to your board
5. Select firmware bin and set offset to 0x0
6. Flash
7. Not alive after reset

**Comment by redmushie** [comment]
Thanks. Step 3/4/5/6 is what I needed.

I went to check the latest artifacts on the `develop` pipeline but they've already expired:
![image](https://github.com/OpenShock/Firmware/assets/82113471/93be8788-dfd4-4d15-8a84-82cd6fc059ab)

(Expiry is set to 1 day by default. I'll probably change this soon)

Can you tell me where you got the exact artifact from? I.e. not the download link but a link to the place _where you found_ the download link. Thanks

**Comment by LucHeart** [comment]
Dafuq? At what run are you looking at? Am looking at latest develop. Link here: https://github.com/OpenShock/Firmware/actions/runs/6400794452

**Comment by LucHeart** [comment]
nvm my bad, its the captive portal fix branch - had the same on develop tho

**Comment by redmushie** [comment]
XD

**Comment by redmushie** [comment]
I bumped retention to 7 days for the merged firmware artifacts on `develop`. Try those when it finishes building @LucHeart

**Comment by LucHeart** [comment]
develop works now, maybe something on the cpative protal branch is broken. I will test more.

**Comment by LucHeart** [comment]
Works aswell now - well sorta - tried erasing flashing before, that seemed to have done the trick.

Another issue that might need to be looked into, the LED doesnt flash, and just in general the captive portal is having issues with the frontend. - Forwarding to @hhvrc . Closing this issue for now.
