### ISSUE TITLE
[Bug] [CI] Restore old naming scheme for release firmware bin

### ISSUE THREAD

**Issue by LucHeart** [OpenShock/Firmware#198]
With 1.1.0 the naming scheme for the firmware merged bin's has changed. It does NOT include the version anymore. This leads to not knowing what firmware version a certain bin is.

This was previously different, dont exactly know why it was changed.

E.g. currently: `OpenShock_Wemos-D1-Mini-ESP32_stable`

What it should really be is something like: `OpenShock_Wemos-D1-Mini-ESP32_stable_1.1.1`
for beta this would be `OpenShock_Wemos-D1-Mini-ESP32_beta_1.1.1-rc.1`

**Comment by hhvrc** [comment]
I would change it to ``OpenShock_Wemos-D1-Mini-ESP32_1.1.1`` rather than ``OpenShock_Wemos-D1-Mini-ESP32_stable_1.1.1``

**Comment by LucHeart** [comment]
just for stable? would keep for beta thought

**Comment by hhvrc** [comment]
This would apply for all release channels
