### ISSUE TITLE
[Feature] Debug override for gateway fqdn

### ISSUE THREAD

**Issue by LucHeart** [OpenShock/Firmware#224]
### Pre-submission checklist

- [X] I checked that there is no other Feature Request describing my wish.
- [X] I checked that this feature is, in fact, not supported.
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### What should be possible that currently is not?

Having a way to override the gateway a device is connecting to for debug purposes would be nice to have.
Main debug reason is backend development in combination with firmware development.

**Comment by hhvrc** [comment]
Implemented in #223
