### ISSUE TITLE
Add central config manager using flatbuffers

### ISSUE THREAD

**Issue by hhvrc** [OpenShock/Firmware#23]
Add central config manager for basic settings that dont get changed that often.

This would be needed because having one file per options is VERY inefficient, each file created takes up 4k bytes in LittleFS so this would clog up the file system fast.

We can implement this when Flatbuffers gets merged into develop because it makes all of this really easy

**Comment by redmushie** [comment]
Add to this that everything should be configurable over serial. That would be a huge improvement for both manual testing and maybe even automatic testing!

**Comment by hhvrc** [comment]
This is implemented and working
