### ISSUE TITLE
[Bug] WiFi reports connection failed, but still connected

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#35]
Got an UI popup that said "connection failed". Serial reports the same: 
![image](https://github.com/OpenShock/Firmware/assets/82113471/59d2b0bd-0338-469a-bfb2-b15fa48bfb46)

However, it still connected.

Board is `Seeed Xiao ESP32-S3`

**Comment by redmushie** [comment]
Might wanna look into why it FAILS to connect instead no?

**Comment by redmushie** [comment]
Postponing to next release due to low importance.

**Comment by LucHeart** [comment]
Stale, closing
