### ISSUE TITLE
0.3-second shock lasts 9 seconds

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#48]
```
  Version:  0.0.0-develop
    Build:  debug
   Commit:  70803fb5a1df141dc72d46cd868c40c5c0b4cfc3
    Board:  Pishock-2023
     Chip:  esp32
```

Title.

**Comment by redmushie** [comment]
I tested with a shock at 25% and it lasted about 4.3 seconds. Very confusing.

**Comment by redmushie** [comment]
It seems to be extremely inconsistent.

![video](https://s.redmushie.me/2023/10/VID_20231018_130729.mp4)

**Comment by redmushie** [comment]
This 0.3s shock lasted **9 seconds**: [https://s.redmushie.me/2023/10/VID_20231018_132005.mp4](https://s.redmushie.me/2023/10/VID_20231018_132005.mp4)

**Comment by hhvrc** [comment]
This is caused due to a change in the flatbuffer schema corrupting the data read, needs investigating why the flatbuffer validator did not catch this.

**Comment by redmushie** [comment]
@hhvrc I disagree since that messes with future protocol changes. It'd put the padding in the middle.
