### ISSUE TITLE
[Feature] Support changing OpenShock server at runtime

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#65]
### Pre-submission checklist

- [X] I checked that there is no other Feature Request describing my wish.
- [X] I checked that this feature is, in fact, not supported.
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### What should be possible that currently is not?

Cofiguring the OpenShock server that the firmware connects to should be modifiable at runtime, not compile time.

- Add serial command to change server
- Add (prefilled) text field with baked-in URL as default value

**Comment by hhvrc** [comment]
Why is this necessary?

**Comment by redmushie** [comment]
Because self-hosting is a primary feature and currently we're hard baking shocklink.net into all binaries.

**Comment by hhvrc** [comment]
Due to this being a change being one that is done very rarely I will not be swapping it at runtime, but will implement it as a set-and-reboot procedure, setting it at runtime introduces alot of complexity

**Comment by redmushie** [comment]
At a glance, I don't think that wouldn't make sense if you're still on the captive portal, since no gateway connection or auth token was acquired yet.

After thinking on it for a bit, I'm of the opinion that the minimum viable is "set and apply after reboot". Rebooting the board the second you change it will:

1. Boot you out of the captive portal network (if changing it that way), and;
2. Mess with attempts at automating configuration, as the serial connection will probably be interrupted, or at the very least be spammed with a large quantity of irrelevant logs. (Though I admit that's usually of little significance.)

**Comment by hhvrc** [comment]
Implemented in #223
